/**
 * Request and pipeline parameter schemas.
 * Ported from python-version/app/models/schema.py.
 *
 * Field names stay snake_case to keep the v1 API contract unchanged.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const VideoConcatMode = {
  random: "random",
  sequential: "sequential",
} as const;
export type VideoConcatModeValue = (typeof VideoConcatMode)[keyof typeof VideoConcatMode];

export const VideoTransitionMode = {
  none: null,
  shuffle: "Shuffle",
  fadeIn: "FadeIn",
  fadeOut: "FadeOut",
  slideIn: "SlideIn",
  slideOut: "SlideOut",
  zoomIn: "ZoomIn",
  zoomOut: "ZoomOut",
} as const;
export type VideoTransitionModeValue =
  | "Shuffle"
  | "FadeIn"
  | "FadeOut"
  | "SlideIn"
  | "SlideOut"
  | "ZoomIn"
  | "ZoomOut"
  | null;

export const VideoAspect = {
  landscape: "16:9",
  portrait: "9:16",
  square: "1:1",
} as const;
export type VideoAspectValue = (typeof VideoAspect)[keyof typeof VideoAspect];

export function aspectToResolution(aspect: VideoAspectValue): [number, number] {
  switch (aspect) {
    case VideoAspect.landscape:
      return [1920, 1080];
    case VideoAspect.portrait:
      return [1080, 1920];
    case VideoAspect.square:
      return [1080, 1080];
    default:
      throw new Error(`unsupported video aspect: ${aspect}`);
  }
}

/** Orientation name used by the Pexels search API. */
export function aspectOrientation(aspect: VideoAspectValue): "landscape" | "portrait" | "square" {
  if (aspect === VideoAspect.landscape) return "landscape";
  if (aspect === VideoAspect.portrait) return "portrait";
  return "square";
}

// ---------------------------------------------------------------------------
// Materials
// ---------------------------------------------------------------------------

export const materialSourceInfoSchema = z
  .object({
    provider: z.string().optional(),
    search_term: z.string().optional(),
    asset_id: z.string().nullable().optional(),
    source_page: z.string().nullable().optional(),
    creator: z
      .object({
        id: z.string().optional(),
        name: z.string().optional(),
        profile_page: z.string().optional(),
      })
      .nullable()
      .optional(),
    rendition: z
      .object({
        id: z.string().nullable().optional(),
        width: z.number().nullable().optional(),
        height: z.number().nullable().optional(),
      })
      .nullable()
      .optional(),
  })
  .passthrough();

export const materialInfoSchema = z.object({
  provider: z.string().default("pexels"),
  url: z.string().default(""),
  duration: z.number().default(0),
  /**
   * Filtered public provenance for a downloaded asset. Rebuilt from a field
   * allow-list before being persisted so signed URLs and credentials supplied
   * by a caller never reach the task record.
   */
  source_info: materialSourceInfoSchema.nullish(),
});
export type MaterialInfo = z.infer<typeof materialInfoSchema>;

// ---------------------------------------------------------------------------
// Video generation parameters
// ---------------------------------------------------------------------------

export const videoParamsSchema = z.object({
  video_subject: z.string(),
  /** Narration text. Generated by the LLM when empty. */
  video_script: z.string().default(""),
  /** Stock search keywords, as a list or a comma-separated string. */
  video_terms: z.union([z.string(), z.array(z.string())]).nullish(),

  video_aspect: z.enum(["16:9", "9:16", "1:1"]).default("9:16"),
  video_concat_mode: z.enum(["random", "sequential"]).default("random"),
  video_transition_mode: z
    .enum(["Shuffle", "FadeIn", "FadeOut", "SlideIn", "SlideOut", "ZoomIn", "ZoomOut"])
    .nullish(),
  video_clip_duration: z.number().int().min(1).default(5),
  video_clip_speed: z.number().default(1.0),
  match_materials_to_script: z.boolean().default(false),
  video_count: z.number().int().min(1).default(1),

  video_source: z.enum(["pexels", "pixabay", "coverr", "local"]).default("pexels"),
  video_materials: z.array(materialInfoSchema).nullish(),

  /** Skips TTS. Whisper can still produce subtitles from this file. */
  custom_audio_file: z.string().nullish(),
  /** Empty auto-detects. */
  video_language: z.string().default(""),

  voice_name: z.string().default(""),
  voice_volume: z.number().default(1.0),
  voice_rate: z.number().default(1.0),

  bgm_type: z.string().default("random"),
  bgm_file: z.string().default(""),
  bgm_volume: z.number().default(0.2),
  /** Shared prompt for every AI music provider. */
  video_music_prompt: z.string().max(2000).default(""),
  /** Legacy Sonilo-only field, still read for old tasks and CLI flags. */
  sonilo_bgm_prompt: z.string().max(2000).default(""),

  subtitle_enabled: z.boolean().default(true),
  subtitle_position: z.enum(["top", "bottom", "center", "custom"]).default("bottom"),
  custom_position: z.number().default(70.0),
  font_name: z.string().default("MicrosoftYaHeiBold.ttc"),
  text_fore_color: z.string().default("#FFFFFF"),
  /** Historically either a boolean or a colour string; both still accepted. */
  text_background_color: z.union([z.boolean(), z.string()]).default(false),
  rounded_subtitle_background: z.boolean().default(false),

  font_size: z.number().default(60),
  stroke_color: z.string().default("#000000"),
  stroke_width: z.number().default(1.5),

  n_threads: z.number().int().default(2),
  paragraph_number: z.number().int().min(1).max(10).default(1),
  video_script_prompt: z.string().max(2000).default(""),
  custom_system_prompt: z.string().max(8000).default(""),
});
export type VideoParams = z.infer<typeof videoParamsSchema>;

// ---------------------------------------------------------------------------
// Narrow requests for the intermediate endpoints
// ---------------------------------------------------------------------------

/** POST /api/v1/subtitle — runs the pipeline through subtitle generation. */
export const subtitleRequestSchema = videoParamsSchema
  .partial()
  .extend({
    video_script: z.string(),
    video_subject: z.string().default(""),
  });

/** POST /api/v1/audio — runs the pipeline through TTS. */
export const audioRequestSchema = videoParamsSchema
  .partial()
  .extend({
    video_script: z.string(),
    video_subject: z.string().default(""),
  });

export const videoScriptRequestSchema = z.object({
  video_subject: z.string().default("春天的花海"),
  video_language: z.string().default(""),
  paragraph_number: z.number().int().min(1).max(10).default(1),
  video_script_prompt: z.string().max(2000).default(""),
  custom_system_prompt: z.string().max(8000).default(""),
});
export type VideoScriptRequest = z.infer<typeof videoScriptRequestSchema>;

export const videoTermsRequestSchema = z.object({
  video_subject: z.string().default(""),
  video_script: z.string().default(""),
  amount: z.number().int().min(1).max(20).default(5),
  match_materials_to_script: z.boolean().default(false),
});
export type VideoTermsRequest = z.infer<typeof videoTermsRequestSchema>;

export const videoSocialMetadataRequestSchema = z.object({
  video_subject: z.string().max(500).default("A day in Shanghai"),
  video_script: z.string().max(8000).default(""),
  language: z.string().max(64).default("auto"),
  platform: z.string().max(64).default("tiktok"),
});
export type VideoSocialMetadataRequest = z.infer<typeof videoSocialMetadataRequestSchema>;

/** POST /api/v1/voices/preview — short or full-script TTS listen. */
export const voicePreviewRequestSchema = z.object({
  voice_name: z.string().min(1),
  voice_rate: z.number().min(0.5).max(2).default(1),
  voice_volume: z.number().min(0).max(5).default(1),
  text: z.string().min(1).max(8000),
});
export type VoicePreviewRequest = z.infer<typeof voicePreviewRequestSchema>;

/** Normalises `video_terms` into a trimmed list, whatever form it arrived in. */
export function normalizeVideoTerms(terms: string | string[] | null | undefined): string[] {
  if (!terms) return [];
  if (Array.isArray(terms)) return terms.map((term) => String(term).trim()).filter(Boolean);
  return String(terms)
    .split(/[,，]/)
    .map((term) => term.trim())
    .filter(Boolean);
}
